### ISSUE TITLE
Error on profile install: page_manager_pages table doesn't exist

### ISSUE THREAD

**Issue by malcomio** [apimanagement/drupalportal#3] opened 2015-07-29 14:50 UTC
When running the installation profile the following error occurs:
```
WD php: Warning: Invalid argument supplied for foreach() in drupal_requirements_severity() (line 1206 of /var/www/drupal7/includes/install.inc).                                                                                                                   [warning]
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal7.page_manager_pages' doesn't exist' in /var/www/drupal7/includes/database/database.inc:2176
```

**Comment by chrisdudley** [comment] 2015-07-31 12:50
I cannot recreate this issue. line 44 of apim_profile.install in apim_profile_install() enables the page_manager module.

What changes have you made locally to run into problems like this?

**Comment by chrisdudley** [comment] 2015-08-03 07:52
Closing as I suspect you've made changes locally that have caused these issues. I cannot reproduce them myself.
The required 'submodules' are all enabled in apim_profile_install(). Only the top level module directories are listed explicitly in the dependencies (this seems consistent with all other drupal install profiles I have seen).

**Closed by chrisdudley** 2015-08-03 07:52 UTC
